[["/local/packages/python-3.10-site-packages/openai/__init__.py",[false,[["Audio",true,2,["Audio","/local/packages/python-3.10-site-packages/openai/api_resources/audio.py",5]],["ChatCompletion",true,2,["ChatCompletion","/local/packages/python-3.10-site-packages/openai/api_resources/chat_completion.py",5]],["Completion",true,2,["Completion","/local/packages/python-3.10-site-packages/openai/api_resources/completion.py",5]],["Customer",true,2,["Customer","/local/packages/python-3.10-site-packages/openai/api_resources/customer.py",5]],["Deployment",true,2,["Deployment","/local/packages/python-3.10-site-packages/openai/api_resources/deployment.py",5]],["Edit",true,2,["Edit","/local/packages/python-3.10-site-packages/openai/api_resources/edit.py",5]],["Embedding",true,2,["Embedding","/local/packages/python-3.10-site-packages/openai/api_resources/embedding.py",5]],["Engine",true,2,["Engine","/local/packages/python-3.10-site-packages/openai/api_resources/engine.py",5]],["ErrorObject",true,2,["ErrorObject","/local/packages/python-3.10-site-packages/openai/api_resources/error_object.py",5]],["File",true,2,["File","/local/packages/python-3.10-site-packages/openai/api_resources/file.py",5]],["FineTune",true,2,["FineTune","/local/packages/python-3.10-site-packages/openai/api_resources/fine_tune.py",5]],["FineTuningJob",true,2,["FineTuningJob","/local/packages/python-3.10-site-packages/openai/api_resources/fine_tuning.py",5]],["Image",true,2,["Image","/local/packages/python-3.10-site-packages/openai/api_resources/image.py",5]],["Model",true,2,["Model","/local/packages/python-3.10-site-packages/openai/api_resources/model.py",5]],["Moderation",true,2,["Moderation","/local/packages/python-3.10-site-packages/openai/api_resources/moderation.py",5]],["APIError",true,2,["APIError","/local/packages/python-3.10-site-packages/openai/error.py",5]],["InvalidRequestError",true,2,["InvalidRequestError","/local/packages/python-3.10-site-packages/openai/error.py",5]],["OpenAIError",true,2,["OpenAIError","/local/packages/python-3.10-site-packages/openai/error.py",5]],["api_key",true,13,null],["api_key_path",true,13,null],["organization",true,13,null],["api_base",true,13,null],["api_type",true,13,null],["api_version",true,13,null],["verify_ssl_certs",true,13,null],["proxy",true,13,null],["app_info",true,13,null],["enable_telemetry",true,13,null],["ca_bundle_path",true,13,null],["debug",true,13,null],["log",true,13,null],["requestssession",true,13,null],["aiosession",true,13,null],["__version__",true,13,null],["__all__",true,13,null]]]]]